apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-web
  namespace: chartfolio
  labels:
    app: assets-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assets-web
  template:
    metadata:
      labels:
        app: assets-web
    spec:
      containers:
      - name: assets-web
        image: harbor.ru.dmitriy.space/library/chartfolio-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: assets-web
  namespace: chartfolio
spec:
  selector:
    app: assets-web
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP